### ISSUE TITLE
include index.js to help with creating includePaths?

### ISSUE THREAD

**Issue by pdehaan** [eduardoboucas/include-media#108]
Something like https://github.com/ranjandatta/node-normalize-scss/blob/master/index.js

This would allow us to easily add **include-media** to the Sass includePath without needing to reach into the node_modules directory.

---

I was able to get this working, but I had to use the following code:

```scss
@import "../node_modules/include-media/dist/include-media";

$hidpi: "retina2x";

#foo {
  @include media($hidpi) {
    content: 'Device Pixel Ratio of at least 1.5';
  }
}
```
