### ISSUE TITLE
Output mobile first media queries by default

### ISSUE THREAD

**Issue by slavanga** [eduardoboucas/include-media#112]
If no operator is specified with a breakpoint key an error gets thrown. Would it be possible to fall back to a min-width media query (>= operator) if one of the keys in ```$breakpoints``` is used without an operator?

That would be very convenient since that type of media query is probably used most of the time.

**Input:**
```scss
@include media(phone) {
    width: 50%;
}
```

**Desired output:**
```css
@media (min-width: 320px) {
    width: 50%;
}
```

**Comment by eduardoboucas** [comment]
This syntax is similar to the one used by [Sass MQ](https://github.com/sass-mq/sass-mq), I believe. 

This is not difficult at all to implement, but I wonder if `@include media(phone)` is as self-explanatory as `@include media('>=phone')`. Some people might think "this affects everything **above** phone", whilst other people might think "this affects **only** phone".

What are your thoughts?

**Comment by Nirazul** [comment]
You can tweak include-media yourself to show this behaviour. I have it in use for quite a few projects so far:

```scss
//** Break point definitions for the "include-media" SCSS plugin. **//
// usage: >xs  or: <=xs
$breakpoints: (
    xs:  $screen-xs-max,
    sm:  $screen-sm-max,
    md:  $screen-md-max
);


//** Media expressions for the "include-media" SCSS plugin. **//
$media-expressions: (
    xs: '(max-width: #{$screen-xs-max})',
    sm: ('(min-width: #{$screen-sm-min}) and (max-width: #{$screen-sm-max})'),
    md: ('(min-width: #{$screen-md-min}) and (max-width: #{$screen-md-max})'),
    lg: '(min-width: #{$screen-lg-min})',
);
```
