### ISSUE TITLE
Fails, when given null

### ISSUE THREAD

**Issue by Nirazul** [eduardoboucas/include-media#121]
I have a few mixins for flex-grid scaffolding in which I'm using `include-media`. For example:

```scss
///
/// Method adding spacing between items.
/// @param {String} $selector - A root module name (BEM) including a dot. Default: Current selector.
/// @param {String} $media-expression - A media expression that is parseable by `include-media`.
/// @param {Number} $sz-gutter - The desired gutter size in any spacial unit.
/// @param {String} $item-modules - One or multiple BEM submodule names without dashes.
///
@mixin grid--gutter($selector: null, $media-expression: null, $sz-gutter: 0, $item-modules...) {
    @include media($media-expression) {
        $item-modules-selectors: grid--item-module-list($selector, $item-modules);

        #{$selector}--container {
            padding-left: ($sz-gutter * 2);
            padding-right: ($sz-gutter * 2);
        }

        #{$selector}--row {
            margin-left: -$sz-gutter;
            margin-right: -$sz-gutter;
        }

        #{$item-modules-selectors} {
            padding-left: $sz-gutter;
            padding-right: $sz-gutter;
        }
    }
}
```

I've voluntarily decided to leave `$media-expression` optional, so I can easily style the general case:
```scss
@grid--gutter('.my-module', null, 12px);
// and/or
@grid--gutter('.my-module', 'xs', 6px);
```

Unfortunately, include media fails when it receives `null` as only parameter:
```
Details:
    formatted: Error: argument `$string` of `str-index($string, $substring)` must be a string

       Backtrace:
       	../assets/src/scss/app/vendor/_include-media.scss:267, in function `str-index`
       	../assets/src/scss/app/vendor/_include-media.scss:267, in function `get-expression-operator`
       	../assets/src/scss/app/vendor/_include-media.scss:367, in function `parse-expression`
       	../assets/src/scss/app/vendor/_include-media.scss:556, in mixin `media`
       	../assets/src/scss/app/layout/_grid.scss:59, in mixin `grid--gutter`
       	../assets/src/scss/app/layout/_grid.scss:158, in mixin `grid--gutter-base`
       	../assets/src/scss/app/molecule/form/_grid.scss:20
        on line 267 of ../assets/src/scss/app/vendor/_include-media.scss
>>     @if str-index($expression, $operator) {
   --------^
```

What I've done is to duplicate the function and add a separate call, when `$media-expression` is null. But this leads to the doubled amount of mixins, which I'm trying to reduce.
Is there a possibility that you'd cover the case of receiving null by just writing `@content`?

I haven't found any nullish data-type I could provide instead of `null`, which would work like `@include media() { /* stuff */ }`

**EDIT**: I could monkey patch the mixin by changing it to:
```scss
@mixin media($conditions...) {
  // scss-lint:disable SpaceAroundOperator
  @if ($im-media-support and length($conditions) == 0) or
      (not $im-media-support and im-intercepts-static-breakpoint($conditions...)) {
    @content;
  } @else if ($im-media-support and length($conditions) > 0) {
    @if nth($conditions, 1) == null {
      @content;
    } @else {
      @media #{unquote(parse-expression(nth($conditions, 1)))} {
        //Recursive call
        @include media(slice($conditions, 2)...) {
          @content;
        }
      }
    }
  }
}
```

**Comment by HugoGiraudel** [comment]
Hello.

Rather than forking include-media, why don’t you make your code handle this case? I would argue it’s easy enough to do.

```scss
///
/// Method adding spacing between items.
/// @param {String} $selector - A root module name (BEM) including a dot. Default: Current selector.
/// @param {String} $media-expression - A media expression that is parseable by `include-media`.
/// @param {Number} $sz-gutter - The desired gutter size in any spacial unit.
/// @param {String} $item-modules - One or multiple BEM submodule names without dashes.
///
@mixin grid--gutter($selector: null, $media-expression: null, $sz-gutter: 0, $item-modules...) {
  @if $media-expression {    
    @include media($media-expression) {
      $item-modules-selectors: grid--item-module-list($selector, $item-modules);

      #{$selector}--container {
        padding-left: ($sz-gutter * 2);
        padding-right: ($sz-gutter * 2);
      }

      #{$selector}--row {
        margin-left: -$sz-gutter;
        margin-right: -$sz-gutter;
      }

      #{$item-modules-selectors} {
        padding-left: $sz-gutter;
        padding-right: $sz-gutter;
      }
    }
  }
}
```

**Comment by Nirazul** [comment]
@HugoGiraudel 
That's the way I've done it until now. I've ended up with double the amount of functions. Let me provide an example:

```scss
@mixin _grid--scaffold() { /* the stuff i really wanna include */ }
@mixin grid--scaffold() { @if $media-expression { @include _grid--scaffold(); } @else { _grid--scaffold(); } }

@mixin _grid--root() { /* the stuff i really wanna include */ }
@mixin grid--root() { @if $media-expression { @include _grid--root(); } @else { _grid--root(); } }

/* ...and so forth */
```

It's cumbersome to have two mixins for one usage and bloats the grid plugin.
Also, I think it's a bit of an inconsistency to say that `@include media() {}` doesn't do the same thing as `@include media(null) {}`.

**Comment by HugoGiraudel** [comment]
I am sorry but I don’t get it.

**Comment by Nirazul** [comment]
Ok I'll try it with a full example:

I'm forced to use this pattern for *every* mixin I'm using, that has a `$media-expression`.

```scss
///
/// Internal method that adds spacing between items.
///
@mixin _grid--gutter($selector, $sz-gutter, $item-modules) {
    $item-modules-selectors: grid--item-module-list($selector, 'item', $item-modules);

    #{$selector}--container {
        padding-left: ($sz-gutter * 2);
        padding-right: ($sz-gutter * 2);
    }

    #{$selector}--row {
        margin-left: -$sz-gutter;
        margin-right: -$sz-gutter;
    }

    #{$item-modules-selectors} {
        padding-left: $sz-gutter;
        padding-right: $sz-gutter;
    }
}

///
/// External method that feeds `_grid--gutter` depending on a certain media-expression.
///
@mixin grid--gutter($selector, $media-expression, $sz-gutter, $item-modules...) {
    @if $media-expression {
        @include media($media-expression) {
            @include _grid--gutter($selector, $sz-gutter, $item-modules);
        }
    } @else {
        @include _grid--gutter($selector, $sz-gutter, $item-modules);
    }
}
```

I could get rid of `_grid--gutter` when `include-media` would handle a null like no value.
