### ISSUE TITLE
Enhancement: Reduce bloat in output

### ISSUE THREAD

**Issue by indrekpaas** [eduardoboucas/include-media#13]
Great mixin! It could introduce some sort of intelligence to reduce bloat in output.

The following example (with the default setup)

```scss
div {
  display: none;

  @include media(">=phone", "<tablet") {
    display: block;
  }
}
```

produces

```css
div {
  display: none;
}
@media (min-width: 320px) and (max-width: 767px) {
  div {
    display: block;
  }
}
```

whereas `phone` is the first device in `$breakpoints` and more importantly with the smallest value on the range, and could as effectively be output as

```css
div {
  display: none;
}
@media (max-width: 767px) {
  div {
    display: block;
  }
}
```

The same principle can be applied at the upper end of the range.

**EDIT:** To further explain the benefit: it doesn't make sense applying a media query to smallest and largest denominators. We're not capping our styles with `(max-width: 8000px)`, why would we limit them to `(min-width: 320px)`.
