### ISSUE TITLE
dppx in retina expressions  – do we need it?

### ISSUE THREAD

**Issue by jakob-e** [eduardoboucas/include-media#142]
According to [caniuse](http://caniuse.com/#feat=css-media-resolution) IE11- and iOS Safari does not support dppx or dpcm – is there a case where we are not covered by dpi's and ratio?

Ref: https://github.com/eduardoboucas/include-media/issues/128

**Comment by Nirazul** [comment]
My opinion: As dppx is the new defacto standard for resolution media queries it wouldn't be a sensitive decision concerning a future proof solution. 
Another pro argument is the fact that autoprefixer will expand `dppx` by the corresponding webkit query, but obviously not the other way around. As most web devs nowadays will rely on autoprefixer the code quality would suffer, removing coverage instead of improving it.

**Comment by jakob-e** [comment]
@Nirazul 

> As dppx is the new defacto standard for resolution media queries

– Not seeking a lengthy debate but when did this happen – any references to back it up?

> autoprefixer will expand dppx by the corresponding webkit query

– It does the same if you use dpi!?

````CSS
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx) {
  .example { color: red; }
}
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .example { color: blue; }
}
`````
----


As dpi's are not deprecated – both queries are equally future proof
````CSS
@media (min-resolution: 2dppx) {} 
@media (min-resolution: 192dpi) {}
`````
... the last one will just support about 5 - 10% more browsers :-)
