### ISSUE TITLE
Force a convention on inclusive operators

### ISSUE THREAD

**Issue by tzi** [eduardoboucas/include-media#145]
Hi include-media team!

Thanks for this awesome tool.
I really love it :tada: 

I want to open a discussion about the purpose of switching between inclusive and exclusive operators.
According to the website, it's "for a finer control over the intervals".

For me, this fine tunning is a source of mistakes and bugs.

```scss
// It's a bad example, and there is a lot of way of writing this CSS right
// But the important part, this code introduces a bug
// Nothing obvious, at the exact tablet resolution the sidebar is full width
.sidebar {
    float: left;
    width: 100%;
    @include media('>phone', '<tablet') {
      width: 50%;
    }
    @include media('>tablet') {
      width: 30%;
    }
}
```

After a couple of days using it in my team, we decided to setup a convention: always use '<' or '>='.
I do not see any advantage of the fine control :disappointed: 

**Do you think this library could stop allow '<=' and '>=' operator?**
The operator '<' could always be exclusive and the '>' always inclusive.

Cheers,
Thomas.

**Comment by robsonsobral** [comment]
Well, this doesn't look nothing new to me. It's a problem we're facing with media queries since they were created.

Did you never see media queries like `max-width: 960px` and `min-width: 960px` on the same file?

**Comment by HugoGiraudel** [comment]
> Do you think this library could stop allow '<=' and '>=' operator?

With all due respect Thomas, no. If you don’t like them, don’t use them. If you want to forbid them, override the mixin with your own layer to throw if it happens. Easier probably, writer a linter to prevent that.

**Comment by eduardoboucas** [comment]
What @HugoGiraudel said. I'm afraid we can't afford to completely break the API and remove features that other people find useful just because you don't need them or don't find them convenient.

Closing.

**Comment by tzi** [comment]
> Well, this doesn't look nothing new to me. It's a problem we're facing with media queries since they were created.
> 
> Did you never see media queries like max-width: 960px and min-width: 960px on the same file?

Nope. It's a misusage of the media quieries for me.
But it is a classic mistake.

> If you don’t like them, don’t use them. If you want to forbid them, override the mixin with your own layer to throw if it happens. Easier probably, writer a linter to prevent that.

Thanks @HugoGiraudel for you constructive answer.
Indeed, we are in discussion for either use a linter or stop using it.

> I'm afraid we can't afford to completely break the API and remove features that other people find useful just because you don't need them or don't find them convenient.

I understand that it is a big change, and that you closed this issue.
It will need a release of a major version to *remove* a feature.

I really understand it.
I maintain open source project by my own.
It was just an issue to start the discussion, maybe other users will give their opinion here.

But I am really curious :smile_cat:  
Do you have any example where you want to use inclusive and exclusive comparison for the same operator and breakpoint?

Thanks for maintaining this lib!

Cheers,
Thomas.

**Comment by HugoGiraudel** [comment]
> Thanks @HugoGiraudel for you constructive answer.

Sarcasm much or were you actually thankful? 😄

> Do you have any example where you want to use inclusive and exclusive comparison for the same operator and breakpoint?

To be fair, no. But I tend to go very simple with my breakpoints. Point is: include-media is all about the syntax. This operator-based approach is what made it what it is. I don’t think it would make sense to remove some operators for whatever reason. That would seem needlessly opinionated.

**Comment by tzi** [comment]
> Sarcasm much or were you actually thankful? :smile:

It was a real thanks!
You took the time to find several solutions and a POC of code.
There is no place for sarcasam in open source :face_with_thermometer:

**Comment by eduardoboucas** [comment]
> Do you have any example where you want to use inclusive and exclusive comparison for the same operator and breakpoint?

There are features of the library that I've never used. There were additions to the library that I knew I'd hardly ever use. But the whole principle, from the beginning, was to provide a simple, natural syntax to cover as many options as possible _whilst_ maintaining compatibility with previous versions.

I remember hearing comments saying that we shouldn't have the `<` and `<=` operators at all, as you should only be writing `min` media queries, but I'm not entitled to enforce best practices or opinions. The library allows you to do whatever you want and you take it from there.

> It was just an issue to start the discussion, maybe other users will give their opinion here.

I appreciate that and discussion is always good. I didn't mean to look dictatorial by closing the issue, but the truth is that even if 100 people say they are for removing the operator, I'm still against it, because someone will see their code breaking for no legitimate reason.

**Comment by tzi** [comment]
We will certainly go for the override solution, thanks again @HugoGiraudel: 
```scss
@mixin at-media($conditions...) {
  @each $condition in $conditions {
    $operator: get-expression-operator($condition);
    @if index(('<=', '≤', '>'), $operator) {
      @error '#{$operator} is not allowed in at-media(#{$condition}).';
    }
  }

  @include media($conditions...) {
    @content;
  }
}
```

Another solution, could be a configuration of banned/allowed operators :relaxed: 

I'll stop bothering you, now.

Cheers,
Thomas.
