### ISSUE TITLE
mixing units and $im-no-media-breakpoint

### ISSUE THREAD

**Issue by robsonsobral** [eduardoboucas/include-media#148]
To use `em` on media-queries is recommended, excepted when you need to set something related to an image. Then, you use `px`.

Everything goes fine until we set `$im-media-support` as `false`. Isn't possible to compare the `$im-no-media-breakpoint` set as `em` to other breakpoints set using `px`. The function `to-length` returns a not useful error message:

```
cannot compare numbers with incompatible units on line 469:11 of _src/stylesheets/vendor/_include-media.scss
```
Being line 469:

```sass
  @return $value * map-get($units, $unit);
```

I tried to think on a solution for it, but I'm too tired. Any ideas, guys?

Thank you for your attention.

**Comment by eduardoboucas** [comment]
`$im-no-media-breakpoint` is defined as a String, corresponding to the name of the breakpoint to emulate when support for media queries is disabled.

See [here](http://include-media.com/documentation/#variable-im-no-media-breakpoint).

**Comment by robsonsobral** [comment]
I understand that, @eduardoboucas . My problem is with the intersection calc:

> Media queries that start at or intercept the breakpoint will be displayed, any others will be ignored.

To test, create all breakpoints using `em`. Then, add somewhere a plain width breakpoint: 

```sass
	@include media('>=600px') {
		background-image: url('/images/foo/bar-600x327.jpg');
	}
```

**Comment by eduardoboucas** [comment]
Okay, I was able to replicate the issue. A couple of things, though:

1. Why would you define a custom media query using different units than the ones you defined your breakpoints map with?
1. The answer to your problem implies include-media knowing how to convert between different units, which it doesn't. Adding that functionality is something I'd like to stay away from.

**Comment by robsonsobral** [comment]
1. because every part needs the best unit for the job. The images are on `px`, so everything related to them should be too.An example? Sometimes we need to align elements to "part" of an image;
2. I wasn't expecting nothing different from you.

I've slept for some hours now. An idea came ([from you](https://gist.github.com/eduardoboucas/84144cd85cbd2ad4db1ca8b902585ca0)):

```scss
@function _im-to-px($breakpoints, $base-value: 16px) {
	$new-breakpoints: ();

	@each $name, $value in $breakpoints {
		$px-value: ($value / 1em) * $base-value;
		$new-breakpoints: map-merge($new-breakpoints, ($name: $px-value));
	}

	@return $new-breakpoints;
}
$im-media-support: false;
$breakpoints: _im-to-px($breakpoints);
```

It works. Annoying, I know. This is why I never change the `html` `font-size`, only the `body`.

Is it possible to improve the error message?

Thank you again, @eduardoboucas ! I'm sorry for bother you.
