### ISSUE TITLE
Undefined mixin 'media'

### ISSUE THREAD

**Issue by mfive** [eduardoboucas/include-media#170]
hmm did i miss something or do i have to also install/include neat? as following appears:

Undefined mixin 'media'

**Comment by jackmcpickle** [comment]
@mfive neat is not required. You must be including it wrong if the mixin isn't available.

**Comment by mfive** [comment]
thanx jack!
i just do an:

@import url("_include-media.scss");

and than - as in the docs - i should be able to use it like this: but how about assignin inside CSS class? this i missing in the docs...is it correct as i try to use it below?

$breakpoints: (phone: 320px, tablet: 768px, desktop: 1024px);
body {
  @include media(">phone") {
    background: rebeccapurple;
  }
}

**Comment by jackmcpickle** [comment]
@mfive You cant use `url()` function to import a scss/sass file as it is valid css.
See http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import
just `@import "include-media";` is usually fine, so long as the file is in the right location.

**Comment by mfive** [comment]
hmm understand but i dont know why: this doesnt work either now:

> @import "include-media";

file is in same directory as in importing .css file:

```
/directory/file-which-imports-include-media.css
/directory/_include-media.scss
```

seems sass is slighty more complex than i thought :)

**Comment by jackmcpickle** [comment]
Are you importing above the block of code you are including the mixin?

**Comment by mfive** [comment]
i am importing the css file with a standard link-tag. is that what you mean?

<link href="/directory/file-which-imports-include-media.css" rel="stylesheet">

**Comment by jackmcpickle** [comment]
No as in.

```scss
@import 'include-media';

@include media('>=phone') {
  .some-class { content: 'phone-media-query'; }
}
```

not 

```scss
@include media('>=phone') {
  .some-class { content: 'phone-media-query'; }
}

@import 'include-media';
```
