### ISSUE TITLE
allow space near operator

### ISSUE THREAD

**Issue by yukulele** [eduardoboucas/include-media#172]
for better readability allow use space near operator 

example:

```scss
// this works
@include media('height<phone') {}

// and this should work
@include media('height < phone') {}
```

**Comment by milewski** [comment]
this is currently the only thing avoiding me to use this lib for ages..

**Comment by black7375** [comment]
It looks like you just need to remove the spaces before evaluating the condition.

https://github.com/eduardoboucas/include-media/blob/master/src/_media.scss#L35-L42

=>
```scss
  } @else if ($im-media-support and length($conditions) > 0) {
    $condition: str-remove-whitespace(nth($conditions, 1));
    @media #{unquote(parse-expression($condition))} {
      // Recursive call
      @include media(slice($conditions, 2)...) {
        @content;
      }
    }
  }
```


`str-remove-whitespace` function is as follows:
```scss
@function str-remove-whitespace($str) {
  $index: str-index($str, ' ');

  @while ($index != null) {
    $str: str-slice($str, 0, $index - 1) + str-slice($str, $index + 1);
    $index: str-index($str, ' ');
  }
  @return $str;
}
```
