### ISSUE TITLE
Define a default media-expression

### ISSUE THREAD

**Issue by kevinbism** [eduardoboucas/include-media#204]
Is it possible to define a default media-expression? For example:

`$im-media-expressions: 'screen' !default;`

Result:
`@include media('>desktop');`
`@media screen and (min-width:1025px) {};`

Actually I always need to define 'screen' everytime I call the function.

**Comment by Toddses** [comment]
Seems like might be using the mixin incorrectly.

`@include media('>desktop);` is incorrect syntax.

```scss
@include media('>desktop') {
  // desktop specific styles
}
```
is the correct usage.

**Comment by jackmcpickle** [comment]
@kevinbism the `!default` flag only sets the variable as a default fallback value. Unfortunately there is no way to set a value in the media query itself as a default query. 

You could however wrap the mixin in another with your own. EG
```scss
@import "include-media";

@mixin screen-media($query) {
  @include media('screen', $query) {
   @content
  }
}

@include screen-media('>desktop') {
    .this {
        content: 'that';
    }
}
```

See https://gist.github.com/jackmcpickle/adb3292456fd6664d93c280ca9d1bbfb
