### ISSUE TITLE
Help needed- setup

### ISSUE THREAD

**Issue by codiejay** [eduardoboucas/include-media#212]
Please how can I properly set up @Includ-media in my scss project? 
I can't find a proper example, please I'll appreciate any help at all. 

NOTE: I have ran `yarn add include-media` 

here's what my file contains now:  

```
//overwrites and states && variables
@import url(//db.onlinewebfonts.com/c/7b50cc294a705c6968947e1786ae546a?family=Komu+A);
@import url('/Assets/Fonts/Estricta/stylesheet.css');

* { 
  padding: 0;
  margin: 0;
  box-sizing: border-box;
}
body { 
  width: 80vw;
  margin: 0 auto;
  padding: 3rem 0;
}
$headingFont: "Komu A", sans-serif;
$textFont: "Estricta", sans-serif;
$mainColo: #FFF5EA;
$darkColor: #040F20;
$fancyColor: #F46095;
$PrimaryFade: #FFECD8; 
$secondaryFade: #FF8600;

//header 
header { 
  font-family: $headingFont;
  display: grid;
  grid-template-columns: 2fr 8fr 1fr;
    ul { 
      text-align: right;
        li { 
          text-decoration: none;
          list-style: none;
            a { 
              color: $darkColor;
            }
        }
    }
}

//showcase 

//course section 

//about 

//newsletter 

//call to action 

//footer 


/*Reponsitivity starts here*/
```

**Comment by Supportic** [comment]
After installing it with npm it depends how your stack looks like. If you are using any bundler like webpack you would need to configure that it should consider the file when bundling.
The easiest way is to go to the `dist` folder from this repo and download the sass file. Afterwards put it in your sass files and import it `@import`. This would work but import will get deprecated at some point.

**Comment by codiejay** [comment]
@Supportic thanks a lot. 

i am just using this in a basic html/scss stack. nothing serious at all. 
but when i import like so: `@import (...)` 
I can't see to understand how to use it 

when i do 
```@include media("phone") {
header {display: 'none'}
}``` 

I get a `media isn't a mixin` error in my live sass compiler.

**Comment by Supportic** [comment]
Try this:
```css
.box {
  width: 200px;
  height: 500px;
  background: red;

  @include media('>desktop') {
    background: blue;
  }
}
```
or this
```css
.box {
  width: 200px;
  height: 500px;
  background: red;
}

@include media('>desktop') {
  .box {
    background: blue;
  }
}
```
