### ISSUE TITLE
`print` support

### ISSUE THREAD

**Issue by trajano** [eduardoboucas/include-media#226]
Can you include a way of determining "print" and also the page sizes like width = 8.5in

**Comment by jackmcpickle** [comment]
Not sure what you mean exactly @trajano 

You can already do print media queries. But setting page width needs to be done inside the `@page` selector. 

This is valid code. 
```scss
@include media('print') {
    @page {
      size: 5.5in 8.5in;
    }
}
```
