### ISSUE TITLE
Using media with variables

### ISSUE THREAD

**Issue by gabriel403** [eduardoboucas/include-media#228]
We're trying to use variables as we do some calcs with this later, but this doesn't seem to work, it just uses the original value

```
$width: 390px;
@include media("<desktop") {
  $width: 320px;
}
```

any hints would be appreciated!

**Comment by gabriel403** [comment]
Haha I'm actually reopening this, when using the above solution what actually happens is the variable inside the media is always being detected, so in my example the width variables is always 320 regardless of size

**Comment by jackmcpickle** [comment]
@gabriel403 not quite sure on your desired output. But css variables are quite powerful and well supported now. CSS variables work like normal css properties (work within the cascade) Where as scss/sass variables would only work for that block at compile time. 

```scss
:root {
  --bg-color: red;
}

@include media("<desktop") {
 :root {
    --bg-color: blue;
  }
}

.my-element {
  background-color: var(--bg-color);
}
```

See codepen - https://codepen.io/jackmcpickle/pen/zYmbLyL
