### ISSUE TITLE
Equal operator: @include query("=phone", "= desktop") {} - Selects only "tablet" or "desktop"

### ISSUE THREAD

**Issue by camya** [eduardoboucas/include-media#229]
This is a feature request to make it possible to use the equal sign to directly address phone, tablet, or desktop.

Examples: 
```css
// phone only
@include query("=phone") {}

// tablet only
@include query("=tablet") {}

// tablet or desktop only
@include query("=tablet", "=desktop") {}
```

In order to make this work, there must be a **start and end width** for each entry.

phone: (width >= 1px) and (width <= 425px)
tablet: (width > 425px) and (width <= 768px)
desktop: (width > 768px) and (width <= 1440px)

```css
// Match only phone, e.g. (width >= 1px) and (width <= 425px)
@include query("=phone") {
  body {
    background-color: red;
  }
}

// Matches both phone and desktop, e.g. ((width >= 1px) and (width <= 425px)) OR ((width > 768px) and (width <= 1440px))
@include query("=phone", "= desktop") {
  body {
    background-color: red;
  }
}
```

Not sure, if this is possible, but it would be a nice addition.
