### ISSUE TITLE
Deprecation Warning: Sass's Behavior for Declarations After Nested Rules

### ISSUE THREAD

**Issue by lhoucinecherif** [eduardoboucas/include-media#232]
I am encountering a deprecation warning when using 'eduardoboucas/include-media' in a Nuxt3 project. The warning message is as follows:
```
Deprecation Warning: Sass's behavior for declarations that appear after nested rules is deprecated.Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls
```

**Comment by jackmcpickle** [comment]
@lhoucinecherif thanks for the heads up. Sounds like a small change. Will check out later this week and see where we get. Otherwise feel free to put a PR up. 😉

**Comment by lhoucinecherif** [comment]
I followed the guidance from [this issue](https://github.com/sass/dart-sass/issues/2280) and managed to silence the warning in my Nuxt app by updating the Nuxt configuration. Here's the relevant part of my nuxt.config.js:
```
vite:  {
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: '@import "@/assets/scss/_variables.scss";',
        api: 'modern',
        silenceDeprecations: ['mixed-decls'],
      },
    },
  },
}
```

**Comment by jackmcpickle** [comment]
Ok. Did some investigation based on the https://sass-lang.com/documentation/breaking-changes/mixed-decls/ new way sass needs to start supporting nesting. 

Doesn't really seem to be a issue with `include-media`.

Basically you should have anything below a mixin inside an selector - as the new way will handle it in a different way and will break your css later on. See the sass link for more info. 

For example

```scss
.test-inside {
  content: 'default';
  @include media('>phone') {
    content: 'phone';
  }
  // Issue is here - current scss standard (but deprecated)
  // This will be pull up below the first content: 'default';
  // New css standard is to render where it is. 
  content: 'default-after';
}
```

Update to the following. 
```scss
.test-inside {
  content: 'default';
  @include media('>phone') {
    content: 'phone';
  }
  // add self nesting rule or clean up css.
  & {
    content: 'default-after';
  }
}
```

You can see the problem here if you just create a simple sass mixin. 
```scss
@mixin breakpointTest($size) {
  @media(min-width: $size) {
    & {
      @content;
    }
  }
}

.example {
  color: red;
  @include breakpointTest(320px) {
    color: blue;
  }
  // This will complain
  color: yellow;
}
```

Hopefully that is enough to show where in your code to update. Although I'm happy to be corrected if you can provide me some example code of it breaking inside `include-media`
