### ISSUE TITLE
Add support for range syntax

### ISSUE THREAD

**Issue by SebastianZ** [eduardoboucas/include-media#239]
Media queries (as well as container queries) support a range syntax besides the known property-colon-value syntax for quite some time now. [According to caniuse.com](https://caniuse.com/css-media-range-syntax), support for it is currently at around 94.9% for tracked browsers.

If this syntax were supported by include-media, it would make it easier to define syntax ranges and also allow to get rid of a bunch of hacky code related to intervals.

Examples:

```scss
@include media(">phone", "<=tablet") {
  width: 50%;
}
```

currently outputs something like this:

```css
@media (min-width: 321px) and (max-width: 768px) {
  width: 50%;
}
```

With support for range syntax the output would look like this:

```
@media (width > 320px) and (width <= 768px) {
  width: 50%;
}
```

The range-based syntax also supports clamping, i.e. to provide two values in one condition. If support for that was added as well, this could then be reduced to something like this:

```scss
@include media(">phone&<=tablet") {
  width: 50%;
}
```

resulting in

```css
@media (320px < width <= tablet) {
  width: 50%;
}
```

Sebastian
