### ISSUE TITLE
Update documentation for declaration aliases

### ISSUE THREAD

**Issue by hudochenkov** [eduardoboucas/include-media#26]
Is there any ability for declarations aliases. For example, I have a lot of phone only styles. I prefer to specify something like:

``` scss
@include media("palm") { }
```

rather than:

``` scss
@include media("<=phone") { }
```

Or for tablet only I want something like:

``` scss
@include media("lap") { }
```

instead of:

``` scss
@include media(">phone", "<=tablet") { }
```

Sure I can use mixins aliases:

``` scss
@mixin lap {
    @include media(">phone", "<=tablet") {
        @content;
    }
}

div {
    @include lap {
        color: red;
    }
}
```

but it's not so flexible if I, for example, want add "retina" declaration for one particular rule.

**Comment by joseluis** [comment]
You can always use variables:
```
$palm: "<=phone";
$lap: ">phone", "<=tablet";

@include media( $palm ) { }
@include media( $lap ) { }
```

**Comment by eduardoboucas** [comment]
I'm afraid that doesn't work @joseluis ([Sassmeister gist]).

@hudochenkov Other libraries, like [Breakpoint-sass](http://breakpoint-sass.com/), use that approach. I guess it wouldn't be hard to add that functionality to include-media. 

I'll have a think about a possible syntax. Feel free to share your thoughts on it as well.

**Comment by joseluis** [comment]
Oops, you're right. The mixin doesn't accept a list as an input.

@eduardoboucas I would like to propose that the mixin detected the type of each argument. In case of a string it would use it as usual. In case of a list then it would iterate through all of the elements treating them as arguments for the mixin.

**Comment by eduardoboucas** [comment]
Sounds good to me!

**Comment by hudochenkov** [comment]
Thank, @joseluis, for idea and proposing pull request :)

I think using variables as parameters is against include-media's philosophy. My idea: create new variable `$aliases` similar to `$media-expressions` (or use it) and in `parse-expression` function parse it, get normal parameters for `media` mixin and run again `parse-expression` with this parameters.

**Comment by joseluis** [comment]
Hi @hudochenkov, I'm curious about why do you think it goes against the philosophy of the project. I belive it supports the motto of using media-queries in a _simple, elegant and maintainable_ way.

Since the ability to use variables as arguments is essentially unavoidable, as it is inherited from the Sass language itself, the idea is to increase the support for that language expectative in a transparent way. It would allow more creative ways to call the media mixin, too.

I also like how the code reads:
```scss
$breakpoints: (phone: 320px, tablet: 768px, desktop: 1024px);

// e.g. aliases using variables
$lap: ">phone", "<=tablet";

@include media( $lap ) { }


// e.g. aliases using map
$bp: (
  lap: (">phone", "<=tablet"),
  phonetop (">phone", "<desktop"),
);

@include media( $bp(lap) );

```

But anyhow, both ideas are not incompatible. I strongly believe the mixin would benefit immensely from being able to receive lists of parameters. But it could also be possible to provide an additional global map for "aliases" if the idea has enough support.

@eduardoboucas what do you think?

**Comment by hudochenkov** [comment]
@joseluis, I've tried your addition and it's not working with case I've created this issue for. And I doesn't explain this case properly :)

For example, I have responsive website and in its SCSS I have a lot styles for tablet and mobile.

```scss
.selector {
	color: black;

	@include media(">phone", "<=tablet") {
		color: green;
	}

	@include media("<=phone") {
		color: blue;
	}
}
```

I don't want repeat each time `">phone", "<=tablet"` so I can create aliases for this:

```scss
$aliases: (
	"lap": (
		">phone", 
		"<=tablet"
	),
	"palm": "<=phone"
) !default;
```

and use these aliases:

```scss
.selector {
	color: black;

	@include media("lap") {
		color: green;
	}

	@include media("palm") {
		color: blue;
	}
}
```

Suddenly I need add to some rules extra parameters:

```scss
.selector2 {
	color: #bada55;

	@include media("lap", "retina2x") {
		color: #b000b5;
	}
}
```

Currently your addition for variables support fails:

```scss
.selector2 {
	color: #bada55;

	@include media($lap, "retina2x") {
		color: #b000b5;
	}
}
```

Even when you resolve this case too, parameters syntax for `media` mixin wasn't be consistant: your `$lap, "retina2x"` vs hypothetical image-media's style `"lap", "retina2x"`.

I'm totally support adding variables for parameters, but also want “native” include-media's support for aliases.
