### ISSUE TITLE
Rewrite the _parse-expression function

### ISSUE THREAD

**Issue by HugoGiraudel** [eduardoboucas/include-media#44]
```scss
/// Get operator of an expression
/// @param {String} $expression - Expression to extract operator from
/// @return {String} - Any of `>=`, `>`, `<=`, `<`, `≥`, `≤`
@function get-expression-operator($expression) {
  @each $operator in ('>=', '>', '<=', '<', '≥', '≤') {
    @if str-index($expression, $operator) {
      @return $operator;
    }
  }

  @error 'No operator found in `#{$expression}`.';
}

/// Get dimension of an expression, based on a found operator
/// @param {String} $expression - Expression to extract dimension from
/// @param {String} $operator - Operator from `$expression`
/// @return {String} - `width` or `height` (or potentially anything else)
@function get-expression-dimension($expression, $operator) {
  $operator-index: str-index($expression, $operator);
  $dimension: str-slice($expression, 0, $operator-index - 1);

  @return if(str-length($dimension) == 0, 'width', $dimension);
}

/// Get dimension prefix based on an operator
/// @param {String} $operator - Operator
/// @return {String} - `min` or `max`
@function get-expression-prefix($operator) {
  @return if(index(('<', '<=', '≤'), $operator), 'max', 'min');
}

/// Get value of an expression, based on a found operator
/// @param {String} $expression - Expression to extract value from
/// @param {String} $operator - Operator from `$expression`
/// @return {Number} - A numeric value 
@function get-expression-value($expression, $operator) {
  $operator-index: str-index($expression, $operator);
  $value: str-slice($expression, $operator-index + str-length($operator));
  
  @if map-has-key($breakpoints, $value) {
    $value: map-get($breakpoints, $value);
  } @else if map-has-key($media-expressions, $value) {
    $value: map-get($media-expressions, $value);
  } @else {
    $value: to-number($value);
  }

  $interval: map-get($unit-intervals, unit($value));

  @if not $interval {
    @error 'Unknown unit `#{unit($value)}`.';
  }

  @if $operator == '>' {
    $value: $value + $interval;
  } @else if $operator == '<' {
    $value: $value - $interval;
  }

  @return $value;
}

/// Parse an expression to return a valid media-query expression
/// @param {String} $expression - Expression to parse
/// @return {String} - Valid media query
@function parse-expression($expression) {
  $operator: get-expression-operator($expression);
  $dimension: get-expression-dimension($expression, $operator);
  $prefix: get-expression-prefix($operator);
  $value: get-expression-value($expression, $operator);
  
  @return '(#{$prefix}-#{$dimension}: #{$value})'
}
```

Relevant SassMeister: http://sassmeister.com/gist/31d4b8c5d88c6deadb1e.
