### ISSUE TITLE
What about vertical responsive behavior?

### ISSUE THREAD

**Issue by sgromskiy** [eduardoboucas/include-media#92]
First of all, this is a very cool thing, thank you guys for it.
But don't forget about vertical responsive behavior. I mean queries with max-height and min-height. It is very important for devices with extra-wide and short(height) screens.
So, please add some functions to handle this problem.
@include media("^700px") {
   some code
}

**Comment by eduardoboucas** [comment]
This exists already:

```scss
@include media('height>700px') {
    // some code
}
```

Or if you want to use pre-defined breakpoints:

```scss
$breakpoints: (
    'tall': 768px
);

@include media('height>tall') {
    // some code
}
```
