### ISSUE TITLE
Option/variable to use px but convert to em

### ISSUE THREAD

**Issue by gunnx** [eduardoboucas/include-media#93]
Sometimes you want to write your breakpoints in px but have them convert to em for the actual media query output

**Comment by HugoGiraudel** [comment]
Do you have a use case?

**Comment by gunnx** [comment]
I've been using another mixin library mq-sass that does this by default, though I prefer it to be a configurable option.

**Comment by eduardoboucas** [comment]
As a side note, have you seen [this](http://fvsch.com/code/em-media-queries/)?

**Comment by gunnx** [comment]
I've read a few articles for the pros and cons, a lot will depend on usage. Its simple enough for me to convert to EM before setting breakpoints.

**Comment by eduardoboucas** [comment]
So if you want to output your media queries in `em`, why do you want to define them as `px`? Is it just to be cleaner on the eye, or is there any other reason?

**Comment by hinok** [comment]
@gunnx What about this approach? Use `em-calc` function, just define it somewhere earlier

```
/// Function converts / calculates px to em
/// @param {number} $size - Width in px
/// @param {number} $base - Base size in px, defaults to 16px
/// @return {number} Width in em
@function em-calc($size, $base: 16px) {
  @return $size / $base * 1em;
}

$breakpoints: (phone: em-calc(640px),
                        tablet: em-calc(768px),
                        desktop: em-calc(1024px));
```

**Comment by gunnx** [comment]
Yes that's basically what I was trying out :+1:

**Comment by eduardoboucas** [comment]
This is a valid use case, but I think this would be a good case for an include-media plugin (like we did with [this one](https://github.com/eduardoboucas/include-media-export)), rather than including this feature in the core.

A very simple plugin could be something like this rough [SassMeister gist](http://sassmeister.com/gist/c3d7d4953d00d10141d3).

**Comment by HugoGiraudel** [comment]
Keep it simple:

```scss
// Plugin starts here
@each $breakpoint, $value in $breakpoints {
  $breakpoints: map-merge($breakpoints, ($breakpoint: ($value / 16px * 1em)));
}
// Plugin ends here
```

**Comment by HugoGiraudel** [comment]
By the way, I would like to see it as a plugin. Sounds good. :)

**Comment by tedw** [comment]
FYI, it's best to always use `em` in media queries to support users who change their default font size:
http://zellwk.com/blog/media-query-units/

**Comment by mrmartineau** [comment]
@HugoGiraudel @eduardoboucas any news on this? the bugs outlined in the [post above](http://zellwk.com/blog/media-query-units/) seem like @HugoGiraudel's fix above should make it into core or the plugin he speaks of.

**Comment by HugoGiraudel** [comment]
Ping @eduardoboucas.

**Comment by eduardoboucas** [comment]
I still don't see why this should go into core, as there is currently nothing stopping you from writing media queries in ems with include-media. Can you elaborate on your requirements, @mrmartineau?

**Comment by mrmartineau** [comment]
I don't mind if it goes into core if there's a plugin that can be added to get to the same outcome. If you read the article linked by @tedw you will see that both Safari and Mobile Safari have bugs when media-queries are defined in `px` and the user has changed their default font-size. I am happy to make the plugin but wouldn't know how to atm.

**Comment by eduardoboucas** [comment]
I'm not arguing against the argument of using `em` instead of `px` in media queries. What I'm saying is, if you do this:

```scss
$breakpoints: (
  'small': 18em,
  'medium': 37em,
  'large': 75em
);
```

... you achieve what you're after. So if I understand correctly, what you're looking for is a convenience method to convert `px` to `em`, which I think is outside the scope of this library.

Does that make sense?

**Comment by mrmartineau** [comment]
Yes, sorry I meant to say that. It is for convenience, and lets face it, laziness, that I want to be able to define the breakpoints in px and then have it convert to em. Having said all this, in [my framework](https://github.com/TryKickoff/kickoff) we have a function to convert px to em which could be used inside the `$breakpoints` map, like so:

```scss
$breakpoints: (
  'small': em(500, 16),
  'medium': em(750, 16),
  'large': em(1000, 16)
);
```

I have kind of talked myself out of this 'fix' 😂  but it still might be useful to have the plugin..

**Comment by eduardoboucas** [comment]
How about this?

```scss
@function im-toEm($breakpoints, $base-value: 16px) {
  $newBreakpoints: ();
  
  @each $name, $value in $breakpoints {
    $emValue: ($value / $base-value) * 1em;
    $newBreakpoints: map-merge($newBreakpoints, ($name: $emValue));
  }
  
  @return $newBreakpoints;
}

$breakpoints: im-toEm((
  'small': 300px,
  'medium': 600px,
  'large': 1200px
));
```
